config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :san_phams
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "san_phams#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/san_pham.rb
class SanPham < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # before_action :authenticate_user!
end

app/controllers/san_phams_controller.rb
class SanPhamsController < ApplicationController
  before_action :set_san_pham, only: %i[ show edit update destroy ]

  # GET /san_phams or /san_phams.json
  def index
    @san_phams = SanPham.all
  end

  # GET /san_phams/1 or /san_phams/1.json
  def show
  end

  # GET /san_phams/new
  def new
    @san_pham = SanPham.new
  end

  # GET /san_phams/1/edit
  def edit
  end

  # POST /san_phams or /san_phams.json
  def create
    @san_pham = SanPham.new(san_pham_params)

    respond_to do |format|
      if @san_pham.save
        format.html { redirect_to san_pham_url(@san_pham), notice: "San pham was successfully created." }
        format.json { render :show, status: :created, location: @san_pham }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @san_pham.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /san_phams/1 or /san_phams/1.json
  def update
    respond_to do |format|
      if @san_pham.update(san_pham_params)
        format.html { redirect_to san_pham_url(@san_pham), notice: "San pham was successfully updated." }
        format.json { render :show, status: :ok, location: @san_pham }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @san_pham.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /san_phams/1 or /san_phams/1.json
  def destroy
    @san_pham.destroy

    respond_to do |format|
      format.html { redirect_to san_phams_url, notice: "San pham was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_san_pham
      @san_pham = SanPham.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def san_pham_params
      params.require(:san_pham).permit(:name, :imgUrl, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/san_phams_helper.rb
module SanPhamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- CSS only -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  
  <body>
    <header>      
      <div class="container-fluid row bg-primary">
        <div class="container">
          <nav class="navbar navbar-dark">  
            <a href="#" style="color:white; font-size:30px; font-weight:bold;">SHOPGAME</a>
            <form class="form-inline">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">   
              <i class="fa-solid fa-magnifying-glass" style="color:white; font-size:20px;"></i>             
            </form>
            <div class="container-inline">    
              <a href="#" style="color:white;">                
                <% if current_user %>
                  <%= current_user.email %>
                  <%= link_to "Đăng xuất", destroy_user_session_path, 'data-turbo-method': :delete, 'style': 'color: white' %>
                <% else %>  
                  <%= link_to "Đăng nhập", new_user_session_path, 'style': 'color: white' %>       
                <% end %>                
              </a>            
            </div>
          </nav>
        </div>
      </div>
    </header>
    <main>      
      <div class="container">        
        <% if notice %>
          <p class="notice"><%= notice %></p>
        <% elsif alert %>
          <p class="alert"><%= alert %></p>
        <% end %>        
        <%= yield %>   
      </div>
    </main>
  </body>
</html>

app/views/san_phams/_form.html.erb
<%= form_with(model: san_pham) do |form| %>
  <% if san_pham.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(san_pham.errors.count, "error") %> prohibited this san_pham from being saved:</h2>

      <ul>
        <% san_pham.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :imgUrl, style: "display: block" %>
    <%= form.text_field :imgUrl %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/san_phams/_san_pham.html.erb
<div id="<%= dom_id san_pham %>">
  <p>
    <strong>Name:</strong>
    <%= san_pham.name %>
  </p>

  <p>
    <strong>Imgurl:</strong>
    <%= san_pham.imgUrl %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= san_pham.price %>
  </p>

</div>

app/views/san_phams/edit.html.erb
<h1>Editing san pham</h1>

<%= render "form", san_pham: @san_pham %>

<br>

<div>
  <%= link_to "Show this san pham", @san_pham %> |
  <%= link_to "Back to san phams", san_phams_path %>
</div>

app/views/san_phams/index.html.erb
<div class="container" style="margin-top: 20px;">
  <div id="san_phams">
    <div class="row">
      <% @san_phams.each do |san_pham| %>
        <div class="col-md-3" style=" padding: 5px">
          <div class="card" style="width: 17rem;">
            <img src="<%= san_pham.imgUrl %>" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis;"><%= san_pham.name %></h5>
              <p class="card-text"><%= san_pham.price %> đ</p>
              <%= link_to "Xem chi tiết", san_pham %>
            </div> 
          </div>        
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/san_phams/new.html.erb
<h1>New san pham</h1>

<%= render "form", san_pham: @san_pham %>

<br>

<div>
  <%= link_to "Back to san phams", san_phams_path %>
</div>

app/views/san_phams/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @san_pham %>

<div>
  <%= link_to "Edit this san pham", edit_san_pham_path(@san_pham) %> |
  <%= link_to "Back to san phams", san_phams_path %>

  <%= button_to "Destroy this san pham", @san_pham, method: :delete %>
</div>